version: '3.1'

services:
    keycloak:
        build:
            context: .
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8081:8080"

volumes:
    fsa_db_disk:
        driver: local
